apiVersion: oathkeeper.ory.sh/v1alpha1
kind: Rule
metadata:
  name: geometrics-api-reports-list
  namespace: geo-ory
spec:
  upstream:
    url: "http://report-query-api.geo-metrics.svc.cluster.local:8080"
  match:
    url: <https:\/\/geometrics\.combaldieu\.fr\/api\/reports$>
    methods:
      - GET
  authenticators:
    - handler: cookie_session
  authorizer:
    handler: allow
  mutators:
    - handler: header
  errors:
    - handler: json
---
apiVersion: oathkeeper.ory.sh/v1alpha1
kind: Rule
metadata:
  name: geometrics-api-reports-create
  namespace: geo-ory
spec:
  upstream:
    url: "http://report-publisher.geo-metrics.svc.cluster.local:8080"
  match:
    url: <https:\/\/geometrics\.combaldieu\.fr\/api\/reports$>
    methods:
      - POST
  authenticators:
    - handler: cookie_session
  authorizer:
    handler: allow
  mutators:
    - handler: header
  errors:
    - handler: json
---
apiVersion: oathkeeper.ory.sh/v1alpha1
kind: Rule
metadata:
  name: geometrics-api-reports-view
  namespace: geo-ory
spec:
  upstream:
    url: "http://report-query-api.geo-metrics.svc.cluster.local:8080"
  match:
    url: <https:\/\/geometrics\.combaldieu\.fr\/api\/reports\/([a-zA-Z0-9_-]+)(?:\/(llm-responses|kpis))?$>
    methods:
      - GET
  authenticators:
    - handler: cookie_session
  authorizer:
    handler: allow
  mutators:
    - handler: header
  errors:
    - handler: json
---
apiVersion: oathkeeper.ory.sh/v1alpha1
kind: Rule
metadata:
  name: geometrics-api-health
  namespace: geo-ory
spec:
  upstream:
    url: "http://report-query-api.geo-metrics.svc.cluster.local:8080"
  match:
    url: <https:\/\/geometrics\.combaldieu\.fr\/api\/health.*>
    methods:
      - GET
  authenticators:
    - handler: noop
  authorizer:
    handler: allow
  mutators:
    - handler: noop
  errors:
    - handler: json